'use client';

import { useEffect, useState } from 'react';
import { api } from '@/lib/api';
import { Settings } from '@/lib/types';
import { Badge, Card, ErrorBox, Loading, PageHeader } from '@/components/UI';

type Source={name:string;url:string;category:string;mode:string};
export default function SettingsPage(){
  const [settings,setSettings]=useState<Settings|null>(null); const [sources,setSources]=useState<Source[]>([]); const [gmail,setGmail]=useState(false); const [error,setError]=useState(''); const [message,setMessage]=useState('');
  useEffect(()=>{api<Settings>('/settings').then(setSettings).catch(e=>setError(e.message));api<Source[]>('/settings/sources').then(setSources);api<{connected:boolean}>('/integrations/gmail/status').then(r=>setGmail(r.connected));},[]);
  if(!settings)return error?<ErrorBox message={error}/>:<Loading/>; const set=(k:keyof Settings,v:any)=>setSettings({...settings,[k]:v});
  const save=async()=>{try{setSettings(await api<Settings>('/settings',{method:'PUT',body:JSON.stringify(settings)}));setMessage('Paramètres enregistrés.');}catch(e:any){setError(e.message)}};
  return <><PageHeader title="Paramètres" description="Règles de recherche, score, rémunération et intégrations." actions={<button className="btn" onClick={save}>Enregistrer</button>}/>{message&&<div className="notice">{message}</div>}{error&&<ErrorBox message={error}/>}<div style={{height:14}}/><div className="grid cols-2">
    <Card><h2 className="section-title">Recherche et score</h2><div className="stack"><label>Postes ciblés (un par ligne)<textarea value={settings.targetJobs.join('\n')} onChange={e=>set('targetJobs',e.target.value.split('\n').map(v=>v.trim()).filter(Boolean))}/></label><label>Exclusions strictes (une par ligne)<textarea value={settings.exclusions.join('\n')} onChange={e=>set('exclusions',e.target.value.split('\n').map(v=>v.trim()).filter(Boolean))}/></label><label>Compétences utilisées pour le score<textarea value={settings.skills.join(', ')} onChange={e=>set('skills',e.target.value.split(',').map(v=>v.trim()).filter(Boolean))}/></label><label>Score minimum pour préparer<input type="number" min="0" max="100" value={settings.matchingThreshold} onChange={e=>set('matchingThreshold',Number(e.target.value))}/></label><label style={{display:'flex',gridTemplateColumns:'auto 1fr',alignItems:'center'}}><input style={{width:'auto'}} type="checkbox" checked={settings.autoPrepare} onChange={e=>set('autoPrepare',e.target.checked)}/> Préparer automatiquement les offres éligibles</label></div></Card>
    <Card><h2 className="section-title">Rémunération</h2><div className="form-grid"><label>TJM Île-de-France<input type="number" value={settings.defaultIdfTjm} onChange={e=>set('defaultIdfTjm',Number(e.target.value))}/></label><label>TJM hors Île-de-France<input type="number" value={settings.defaultOutsideIdfTjm} onChange={e=>set('defaultOutsideIdfTjm',Number(e.target.value))}/></label><label>TJM full remote<input type="number" value={settings.defaultRemoteTjm} onChange={e=>set('defaultRemoteTjm',Number(e.target.value))}/></label><label>TJM minimum<input type="number" value={settings.minimumFreelanceTjm} onChange={e=>set('minimumFreelanceTjm',Number(e.target.value))}/></label><label>TJM maximum<input type="number" value={settings.maximumTjm} onChange={e=>set('maximumTjm',Number(e.target.value))}/></label><label>Salaire CDI minimum<input type="number" value={settings.minimumCdiSalary} onChange={e=>set('minimumCdiSalary',Number(e.target.value))}/></label></div><div className="notice" style={{marginTop:14}}>Fourchette ≤ 500 € : maximum. Au-dessus de 500 € : milieu de la fourchette, plafonné au TJM maximum.</div></Card>
    <Card><h2 className="section-title">Gmail</h2><p className="muted">Connexion OAuth en lecture seule. Aucun mot de passe n’est stocké.</p><div className="actions">{gmail?<><Badge tone="good">Connecté</Badge><button className="btn secondary" onClick={async()=>{await api('/integrations/gmail/disconnect',{method:'POST'});setGmail(false)}}>Déconnecter</button></>:<a className="btn" href="http://localhost:8080/api/integrations/gmail/start">Connecter Gmail</a>}</div></Card>
    <Card><h2 className="section-title">Automatisation</h2><label>Mode d’envoi final<select value={settings.finalSubmissionMode} onChange={e=>set('finalSubmissionMode',e.target.value)}><option value="ONE_CLICK">Confirmation en un clic</option><option value="PREPARE_ONLY">Préparer uniquement</option><option value="AUTOMATIC_AUTHORIZED_ONLY">Automatique uniquement via API autorisée</option></select></label><div className="notice warning" style={{marginTop:14}}>Les CAPTCHA et protections anti-bot ne sont jamais contournés.</div></Card>
  </div><div style={{height:18}}/><Card><h2 className="section-title">Plateformes suivies</h2><div className="table-wrap"><table className="table"><thead><tr><th>Plateforme</th><th>Catégorie</th><th>Mode</th><th></th></tr></thead><tbody>{sources.map(s=><tr key={s.name}><td><strong>{s.name}</strong></td><td><Badge>{s.category}</Badge></td><td>{s.mode}</td><td><a className="btn secondary small" href={s.url} target="_blank">Ouvrir</a></td></tr>)}</tbody></table></div></Card></>;
}
