<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260826143000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Persist deterministic Inbox classification overrides by sender address.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE inbox_sender_classification_rule (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sender_key VARCHAR(255) NOT NULL, category VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_inbox_sender_rule_key ON inbox_sender_classification_rule (sender_key)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE inbox_sender_classification_rule');
    }
}
