<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260805223000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Store CRM contact corrections separately from source records.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE crm_contact_correction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, organization_key VARCHAR(191) NOT NULL, contact_key VARCHAR(255) NOT NULL, corrected_name VARCHAR(255) DEFAULT NULL, corrected_email VARCHAR(254) DEFAULT NULL, corrected_phone VARCHAR(64) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_crm_contact_correction_org_contact ON crm_contact_correction (organization_key, contact_key)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE crm_contact_correction');
    }
}
