<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260809163000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create the user-managed registry of authorized custom scraping sources.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE custom_scraper_source (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, domain VARCHAR(255) NOT NULL, listing_url VARCHAR(2048) NOT NULL, detail_example_url VARCHAR(2048) DEFAULT NULL, mode VARCHAR(16) NOT NULL, enabled BOOLEAN NOT NULL, authorization_confirmed BOOLEAN NOT NULL, authorization_checked_at DATE DEFAULT NULL, authorization_reference TEXT DEFAULT NULL, sync_interval_minutes INT NOT NULL, max_pages INT NOT NULL, max_details INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_custom_scraper_source_listing_url ON custom_scraper_source (listing_url)');
        $this->addSql('CREATE INDEX idx_custom_scraper_source_enabled ON custom_scraper_source (enabled)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE custom_scraper_source');
    }
}
