<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260805110000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Separate canonical job offers from their source occurrences and track merged occurrences.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE source_connector ADD last_merged INT DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE source_connector ALTER last_merged DROP DEFAULT');
        $this->addSql('ALTER TABLE connector_sync_run ADD merged INT DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE connector_sync_run ALTER merged DROP DEFAULT');

        $this->addSql('CREATE TABLE job_source_occurrence (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, job_offer_id INT NOT NULL, source_code VARCHAR(64) NOT NULL, source_name VARCHAR(120) NOT NULL, external_id VARCHAR(180) NOT NULL, source_url VARCHAR(500) DEFAULT NULL, normalized_url VARCHAR(500) DEFAULT NULL, match_type VARCHAR(32) NOT NULL, match_score INT NOT NULL, match_reasons JSON NOT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, raw_data JSON NOT NULL, first_seen_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_seen_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_job_occurrence_offer ON job_source_occurrence (job_offer_id)');
        $this->addSql('CREATE INDEX idx_job_occurrence_url ON job_source_occurrence (normalized_url)');
        $this->addSql('CREATE INDEX idx_job_occurrence_last_seen ON job_source_occurrence (last_seen_at)');
        $this->addSql('CREATE UNIQUE INDEX uniq_job_occurrence_source_external ON job_source_occurrence (source_code, external_id)');
        $this->addSql('ALTER TABLE job_source_occurrence ADD CONSTRAINT FK_JOB_OCCURRENCE_OFFER FOREIGN KEY (job_offer_id) REFERENCES job_offer (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql(<<<'SQL'
            INSERT INTO job_source_occurrence (
                job_offer_id,
                source_code,
                source_name,
                external_id,
                source_url,
                normalized_url,
                match_type,
                match_score,
                match_reasons,
                published_at,
                raw_data,
                first_seen_at,
                last_seen_at
            )
            SELECT
                id,
                COALESCE(NULLIF(source_code, ''), 'legacy-' || id::text),
                COALESCE(NULLIF(source, ''), 'Source historique'),
                COALESCE(NULLIF(external_id, ''), 'legacy-' || id::text),
                source_url,
                CASE
                    WHEN source_url IS NULL OR source_url = '' THEN NULL
                    ELSE regexp_replace(
                        regexp_replace(lower(source_url), '^http://(www\.)?', 'https://'),
                        '/+$',
                        ''
                    )
                END,
                'PRIMARY',
                100,
                '["Offre existante reprise comme occurrence principale."]'::json,
                published_at,
                raw_data,
                discovered_at,
                discovered_at
            FROM job_offer
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE job_source_occurrence DROP CONSTRAINT FK_JOB_OCCURRENCE_OFFER');
        $this->addSql('DROP TABLE job_source_occurrence');
        $this->addSql('ALTER TABLE connector_sync_run DROP merged');
        $this->addSql('ALTER TABLE source_connector DROP last_merged');
    }
}
