<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260824184000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Persist the matching scorer version independently from workflow state';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE job_offer_matching_score_state (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                job_offer_id INT NOT NULL,
                version INT NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_27ED55E83481D195 ON job_offer_matching_score_state (job_offer_id)');
        $this->addSql('ALTER TABLE job_offer_matching_score_state ADD CONSTRAINT FK_JOB_OFFER_MATCHING_SCORE_STATE_JOB FOREIGN KEY (job_offer_id) REFERENCES job_offer (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE job_offer_matching_score_state');
    }
}
