<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260812021500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Store user-confirmed non-sensitive Autofill corrections by site and field fingerprint';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE autofill_correction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, host VARCHAR(255) NOT NULL, field_fingerprint VARCHAR(255) NOT NULL, canonical_key VARCHAR(180) NOT NULL, control_kind VARCHAR(40) NOT NULL, original_value TEXT DEFAULT NULL, corrected_value TEXT NOT NULL, enabled BOOLEAN NOT NULL, usage_count INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_autofill_correction_scope ON autofill_correction (host, field_fingerprint, canonical_key)');
        $this->addSql('CREATE INDEX idx_autofill_correction_host ON autofill_correction (host)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE autofill_correction');
    }
}
