<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260811012500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Persist repeated connector search/import failures in a minimal dead-letter queue.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE connector_dead_letter (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, connector_code VARCHAR(64) NOT NULL, stage VARCHAR(24) NOT NULL, fingerprint VARCHAR(64) NOT NULL, state VARCHAR(24) NOT NULL, failure_count INT NOT NULL, external_id VARCHAR(180) DEFAULT NULL, source_url VARCHAR(500) DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, error_class VARCHAR(255) NOT NULL, error_message TEXT NOT NULL, first_failed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_failed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, resolved_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_connector_dead_letter_fingerprint ON connector_dead_letter (connector_code, stage, fingerprint)');
        $this->addSql('CREATE INDEX idx_connector_dead_letter_state ON connector_dead_letter (state, last_failed_at)');
        $this->addSql('CREATE INDEX idx_connector_dead_letter_connector ON connector_dead_letter (connector_code, state)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE connector_dead_letter');
    }
}
