<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260801190000 extends AbstractMigration
{
    public function getDescription(): string { return 'Initial JobPilot schema'; }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE candidate_profile (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, full_name VARCHAR(180) NOT NULL, email VARCHAR(180) NOT NULL, phone VARCHAR(40) NOT NULL, city VARCHAR(120) NOT NULL, postal_code VARCHAR(20) NOT NULL, mobility VARCHAR(180) NOT NULL, work_authorisation VARCHAR(120) NOT NULL, availability VARCHAR(120) NOT NULL, notice_period VARCHAR(120) NOT NULL, years_of_experience INT NOT NULL, languages JSON NOT NULL, accepted_contracts JSON NOT NULL, work_mode_preference VARCHAR(180) NOT NULL, linkedin_url VARCHAR(255) DEFAULT NULL, portfolio_url VARCHAR(255) DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE user_settings (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, interface_language VARCHAR(8) NOT NULL, target_jobs JSON NOT NULL, exclusions JSON NOT NULL, skills JSON NOT NULL, matching_threshold INT NOT NULL, default_idf_tjm INT NOT NULL, default_outside_idf_tjm INT NOT NULL, default_remote_tjm INT NOT NULL, minimum_freelance_tjm INT NOT NULL, maximum_tjm INT NOT NULL, minimum_cdi_salary INT NOT NULL, salary_includes_total_compensation BOOLEAN NOT NULL, cdd_salary_rule VARCHAR(120) DEFAULT NULL, auto_prepare BOOLEAN NOT NULL, final_submission_mode VARCHAR(40) NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE cv_document (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(180) NOT NULL, original_name VARCHAR(255) NOT NULL, stored_name VARCHAR(255) NOT NULL, language VARCHAR(16) NOT NULL, category VARCHAR(80) NOT NULL, tags JSON NOT NULL, active BOOLEAN NOT NULL, default_for_language BOOLEAN NOT NULL, mime_type VARCHAR(120) NOT NULL, size INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE job_offer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, recommended_cv_id INT DEFAULT NULL, source VARCHAR(100) NOT NULL, source_url VARCHAR(500) DEFAULT NULL, external_id VARCHAR(180) DEFAULT NULL, title VARCHAR(255) NOT NULL, company VARCHAR(255) NOT NULL, client_name VARCHAR(255) DEFAULT NULL, location VARCHAR(255) NOT NULL, contract_type VARCHAR(80) NOT NULL, work_mode VARCHAR(80) NOT NULL, language VARCHAR(8) NOT NULL, description TEXT NOT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, discovered_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, salary_min INT DEFAULT NULL, salary_max INT DEFAULT NULL, tjm_fixed INT DEFAULT NULL, tjm_min INT DEFAULT NULL, tjm_max INT DEFAULT NULL, proposed_tjm INT DEFAULT NULL, proposed_salary INT DEFAULT NULL, score INT NOT NULL, score_reasons JSON NOT NULL, status VARCHAR(50) NOT NULL, prepared_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, raw_data JSON NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_JOB_RECOMMENDED_CV ON job_offer (recommended_cv_id)');
        $this->addSql('CREATE INDEX idx_job_published ON job_offer (published_at)');
        $this->addSql('CREATE INDEX idx_job_score ON job_offer (score)');
        $this->addSql('CREATE TABLE application (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, job_offer_id INT NOT NULL, cv_document_id INT DEFAULT NULL, channel VARCHAR(100) NOT NULL, status VARCHAR(50) NOT NULL, submitted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, message TEXT NOT NULL, cover_letter TEXT NOT NULL, compensation_answer VARCHAR(255) DEFAULT NULL, confirmation_ref VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_APP_JOB ON application (job_offer_id)');
        $this->addSql('CREATE INDEX IDX_APP_CV ON application (cv_document_id)');
        $this->addSql('CREATE TABLE positioning (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, job_offer_id INT DEFAULT NULL, cv_document_id INT DEFAULT NULL, final_client VARCHAR(255) NOT NULL, agency VARCHAR(255) NOT NULL, recruiter_name VARCHAR(180) NOT NULL, recruiter_email VARCHAR(180) DEFAULT NULL, recruiter_phone VARCHAR(50) DEFAULT NULL, mission_title VARCHAR(255) NOT NULL, description TEXT NOT NULL, call_for_tender_reference VARCHAR(180) DEFAULT NULL, advertised_tjm_min INT DEFAULT NULL, advertised_tjm_max INT DEFAULT NULL, advertised_tjm_fixed INT DEFAULT NULL, proposed_tjm INT DEFAULT NULL, accepted_tjm INT DEFAULT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, location VARCHAR(255) NOT NULL, remote_policy VARCHAR(180) NOT NULL, agreement_given_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, proof_email_id VARCHAR(255) DEFAULT NULL, status VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_POSITION_JOB ON positioning (job_offer_id)');
        $this->addSql('CREATE INDEX IDX_POSITION_CV ON positioning (cv_document_id)');
        $this->addSql('CREATE TABLE inbox_message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, gmail_message_id VARCHAR(255) NOT NULL, thread_id VARCHAR(255) NOT NULL, sender VARCHAR(255) NOT NULL, subject VARCHAR(500) NOT NULL, snippet TEXT NOT NULL, received_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, category VARCHAR(50) NOT NULL, processed BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_gmail_message ON inbox_message (gmail_message_id)');
        $this->addSql('ALTER TABLE job_offer ADD CONSTRAINT FK_JOB_RECOMMENDED_CV FOREIGN KEY (recommended_cv_id) REFERENCES cv_document (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE application ADD CONSTRAINT FK_APP_JOB FOREIGN KEY (job_offer_id) REFERENCES job_offer (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE application ADD CONSTRAINT FK_APP_CV FOREIGN KEY (cv_document_id) REFERENCES cv_document (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE positioning ADD CONSTRAINT FK_POSITION_JOB FOREIGN KEY (job_offer_id) REFERENCES job_offer (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE positioning ADD CONSTRAINT FK_POSITION_CV FOREIGN KEY (cv_document_id) REFERENCES cv_document (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE inbox_message');
        $this->addSql('DROP TABLE positioning');
        $this->addSql('DROP TABLE application');
        $this->addSql('DROP TABLE job_offer');
        $this->addSql('DROP TABLE cv_document');
        $this->addSql('DROP TABLE user_settings');
        $this->addSql('DROP TABLE candidate_profile');
    }
}
