<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260812001500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add append-only business timeline events for job opportunities.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TABLE job_timeline_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, job_offer_id INT NOT NULL, application_id INT DEFAULT NULL, type VARCHAR(64) NOT NULL, source VARCHAR(32) NOT NULL, payload JSON NOT NULL, occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, recorded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE INDEX IDX_89B9D7243481D195 ON job_timeline_event (job_offer_id)');
        $this->addSql('CREATE INDEX IDX_89B9D7243E030ACD ON job_timeline_event (application_id)');
        $this->addSql('CREATE INDEX idx_job_timeline_offer_occurred ON job_timeline_event (job_offer_id, occurred_at)');
        $this->addSql('CREATE INDEX idx_job_timeline_type_occurred ON job_timeline_event (type, occurred_at)');
        $this->addSql('ALTER TABLE job_timeline_event ADD CONSTRAINT FK_JOB_TIMELINE_JOB FOREIGN KEY (job_offer_id) REFERENCES job_offer (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE job_timeline_event ADD CONSTRAINT FK_JOB_TIMELINE_APPLICATION FOREIGN KEY (application_id) REFERENCES application (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE job_timeline_event');
    }
}
