<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260812004500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create reusable autofill answer library with profile-backed defaults';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TABLE reusable_answer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, answer_key VARCHAR(120) NOT NULL, label VARCHAR(180) NOT NULL, category VARCHAR(80) NOT NULL, value_source VARCHAR(20) NOT NULL, profile_path VARCHAR(180) DEFAULT NULL, answer_type VARCHAR(20) NOT NULL, answer_fr TEXT DEFAULT NULL, answer_en TEXT DEFAULT NULL, question_patterns JSON NOT NULL, enabled BOOLEAN NOT NULL, sensitive BOOLEAN NOT NULL, auto_fill_allowed BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5DEE260F7F8A65D1 ON reusable_answer (answer_key)');

        $this->seed('availability', 'Disponibilité', 'AVAILABILITY', 'preferences.availability', 'TEXT', [
            'fr' => ['Quelle est votre disponibilité ?', 'Quand pouvez-vous commencer ?', 'Date de disponibilité'],
            'en' => ['What is your availability?', 'When can you start?', 'Available start date'],
        ]);
        $this->seed('notice_period', 'Préavis', 'AVAILABILITY', 'preferences.noticePeriod', 'TEXT', [
            'fr' => ['Quel est votre préavis ?', 'Durée du préavis'],
            'en' => ['What is your notice period?', 'Notice period'],
        ]);
        $this->seed('mobility', 'Mobilité', 'LOCATION', 'preferences.mobility', 'TEXT', [
            'fr' => ['Quelle est votre mobilité ?', 'Zone de mobilité'],
            'en' => ['What is your mobility?', 'Where are you willing to work?'],
        ]);
        $this->seed('work_mode', 'Préférence télétravail / site', 'LOCATION', 'preferences.workModePreference', 'CHOICE', [
            'fr' => ['Préférence télétravail', 'Mode de travail souhaité'],
            'en' => ['Remote work preference', 'Preferred work mode'],
        ]);
        $this->seed('salary_expectation', 'Salaire souhaité', 'COMPENSATION', 'preferences.desiredSalary', 'NUMBER', [
            'fr' => ['Quelles sont vos prétentions salariales ?', 'Salaire souhaité'],
            'en' => ['What are your salary expectations?', 'Desired salary'],
        ]);
        $this->seed('tjm_expectation', 'TJM souhaité', 'COMPENSATION', 'preferences.desiredTjm', 'NUMBER', [
            'fr' => ['Quel est votre TJM ?', 'TJM souhaité', 'Tarif journalier'],
            'en' => ['What is your daily rate?', 'Desired daily rate'],
        ]);
        $this->seed('years_experience', 'Années expérience totale', 'EXPERIENCE', 'professional.yearsOfExperience', 'NUMBER', [
            'fr' => ['Combien années expérience avez-vous ?', 'Années expérience professionnelle'],
            'en' => ['How many years of experience do you have?', 'Years of professional experience'],
        ]);
        $this->seed('symfony_experience', 'Années Symfony', 'EXPERIENCE', 'professional.technologyExperience.Symfony', 'NUMBER', [
            'fr' => ['Combien années expérience avec Symfony ?', 'Expérience Symfony'],
            'en' => ['How many years of Symfony experience do you have?', 'Symfony experience'],
        ]);
        $this->seed('react_experience', 'Années React', 'EXPERIENCE', 'professional.technologyExperience.React', 'NUMBER', [
            'fr' => ['Combien années expérience avec React ?', 'Expérience React'],
            'en' => ['How many years of React experience do you have?', 'React experience'],
        ]);
        $this->seed('vue_experience', 'Années Vue', 'EXPERIENCE', 'professional.technologyExperience.Vue', 'NUMBER', [
            'fr' => ['Combien années expérience avec Vue ?', 'Expérience Vue'],
            'en' => ['How many years of Vue experience do you have?', 'Vue experience'],
        ]);
        $this->seed('work_authorisation', 'Autorisation de travail', 'LEGAL', 'screening.workAuthorisation', 'TEXT', [
            'fr' => ['Avez-vous une autorisation de travail ?', 'Êtes-vous autorisé à travailler en France ?'],
            'en' => ['Are you authorized to work in this country?', 'Do you have work authorization?'],
        ], true, false);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE reusable_answer');
    }

    /** @param array{fr: list<string>, en: list<string>} $patterns */
    private function seed(
        string $key,
        string $label,
        string $category,
        string $profilePath,
        string $answerType,
        array $patterns,
        bool $sensitive = false,
        bool $autoFillAllowed = true,
    ): void {
        $this->addSql(
            'INSERT INTO reusable_answer (answer_key, label, category, value_source, profile_path, answer_type, answer_fr, answer_en, question_patterns, enabled, sensitive, auto_fill_allowed, created_at, updated_at) VALUES (:key, :label, :category, :source, :profilePath, :answerType, NULL, NULL, :patterns, TRUE, :sensitive, :autoFillAllowed, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)',
            [
                'key' => $key,
                'label' => $label,
                'category' => $category,
                'source' => 'PROFILE',
                'profilePath' => $profilePath,
                'answerType' => $answerType,
                'patterns' => json_encode($patterns, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR),
                'sensitive' => $sensitive,
                'autoFillAllowed' => $autoFillAllowed,
            ],
            [
                'sensitive' => \Doctrine\DBAL\ParameterType::BOOLEAN,
                'autoFillAllowed' => \Doctrine\DBAL\ParameterType::BOOLEAN,
            ],
        );
    }
}
