<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260805211500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Store CRM organization notes and display-name corrections separately from source records.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE crm_organization_annotation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, organization_key VARCHAR(191) NOT NULL, display_name VARCHAR(255) DEFAULT NULL, note TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql("COMMENT ON COLUMN crm_organization_annotation.created_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN crm_organization_annotation.updated_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql('CREATE UNIQUE INDEX uniq_crm_organization_annotation_key ON crm_organization_annotation (organization_key)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE crm_organization_annotation');
    }
}
