<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260806063000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Store local CRM follow-up tasks without changing source records.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE crm_follow_up_task (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, organization_key VARCHAR(191) NOT NULL, contact_key VARCHAR(255) DEFAULT NULL, title VARCHAR(180) NOT NULL, note TEXT DEFAULT NULL, due_at DATE NOT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_crm_follow_up_due_status ON crm_follow_up_task (due_at, completed_at)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE crm_follow_up_task');
    }
}
