<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260812231500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create explainable candidate preference and pipeline outcome signals';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TABLE preference_signal (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, job_offer_id INT NOT NULL, application_id INT NOT NULL, signal_type VARCHAR(60) NOT NULL, preference_value SMALLINT NOT NULL, origin VARCHAR(40) NOT NULL, context JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE INDEX IDX_288D506A3481D195 ON preference_signal (job_offer_id)');
        $this->addSql('CREATE INDEX IDX_288D506A3E030ACD ON preference_signal (application_id)');
        $this->addSql('CREATE INDEX idx_preference_signal_type_created ON preference_signal (signal_type, created_at)');
        $this->addSql('CREATE INDEX idx_preference_signal_origin_created ON preference_signal (origin, created_at)');
        $this->addSql('ALTER TABLE preference_signal ADD CONSTRAINT FK_3F38A743928A4CDE FOREIGN KEY (job_offer_id) REFERENCES job_offer (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE preference_signal ADD CONSTRAINT FK_3F38A743E030ACD FOREIGN KEY (application_id) REFERENCES application (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE preference_signal');
    }
}
